name: Node.js Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - '@streamparser/json'
          - '@streamparser/json-whatwg'

    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        # Needs to be explicitly specified for auth to work
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm build
    - run: npm publish --access public -w ${{ matrix.package }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}